model:
  base_learning_rate: 4.5e-6
  target: RestoreFormer.models.vqgan_v1.RestoreFormerModel
  params:
    image_key: 'gt'
    #ckpt_path: /scratch/tnguy231/RFExperiments/tnguy231/logs/2023-12-20T17-34-11_ROHQDROHQD_gpus1_seed76/checkpoints/epoch=000067.ckpt
    schedule_step: [100000, 200000]
    # ignore_keys: ['vqvae.quantize.utility_counter']
    ddconfig:
      target: RestoreFormer.modules.vqvae.vqvae_arch.VQVAEGAN
      params:
        embed_dim: 512
        n_embed: 4096
        double_z: False
        z_channels: 512
        resolution: 512
        in_channels: 3
        out_ch: 3
        ch: 64
        ch_mult: [1,2,2,4,4,8]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        attn_resolutions: [16, 32, 64, 128]
        dropout: 0.0
        enable_mid: True
        fix_decoder: False
        fix_codebook: False
        head_size: 4

    lossconfig:
      target: RestoreFormer.modules.losses.vqperceptual.VQLPIPSWithDiscriminatorWithCompWithIdentity
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10001
        disc_weight: 1.0
        codebook_weight: 1.0
        identity_weight: 1.5
        use_actnorm: False

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12 # per device
    num_workers: 3
    train:
      target: RestoreFormer.data.ffhq_dataset_aug.FFHQAugDataset
      params:
        dataroot_gt: /scratch/tnguy231/FFHQ/image512x512
        io_backend:
          type: disk
        use_hflip: True
        mean: [127.5, 127.5, 127.5]
        std: [127.5, 127.5, 127.5]
        out_size: 512
        gray_prob: 0.008
        gt_gray: True
        exposure_prob: ~
        exposure_range: [0.7, 1.1]
        shift_prob: 0.2
        shift_unit: 1
        shift_max_num: 32
        #validation:
        #  target: RestoreFormer.data.ffhq_dataset_aug.FFHQAugDataset
        #  params:
        #    dataroot_gt: data/val
        #    io_backend:
        #      type: disk
        #    use_hflip: False
        #    mean: [0.5, 0.5, 0.5]
        #    std: [0.5, 0.5, 0.5]
        #    out_size: 512
        #    gray_prob: ~
        #    gt_gray: True
        #    exposure_prob: ~
        #    exposure_range: [0.7, 1.1]
        #    shift_prob: ~
        #    shift_unit: 1
        #    shift_max_num: 32

lightning:
  trainer:
    #devices: "0," # commenting this out defaults to using all GPUs from CUDA_VISIBLE_DEVICES
    accelerator: cuda
    precision: bf16-true
    accumulate_grad_batches: 1
    #max_steps: 256

  profiler: 
    #target: pytorch_lightning.profilers.AdvancedProfiler
    #params:
    #  dirpath: "."
    #  filename: "cprofout"

    #target: pytorch_lightning.profilers.PyTorchProfiler
    #params:
    #  dirpath: perf_logs
    #  filename: log
    #  #emit_nvtx: True
    #  export_to_chrome: True
    #  # profiler kwargs
    #  profile_memory: True
    #  with_flops: True
    #  schedule:
    #    target: torch.profiler.schedule
    #    params:
    #      wait: 10
    #      warmup: 1
    #      active: 3
    #      repeat: 1
